name: Release

on:
  push:
    tags:
      - '*'

jobs:
  pypi-publish:
    name: Create wheel and upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/hashbeaf
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Install the build tools
      run: python -m pip install --upgrade build
    - name: Create the wheel
      run: python -m build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
